# Generated by Django 5.0.4 on 2024-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='x_value',
            field=models.IntegerField(null=True),
        ),
    ]
