# Generated by Django 5.0.6 on 2024-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_event_x_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
