# Generated by Django 5.0.6 on 2024-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_privatecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='particpant',
            name='privatecode',
            field=models.TextField(default='', max_length=50),
        ),
    ]
