# Generated by Django 5.0.6 on 2024-07-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_event_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Particpant',
            new_name='Participant',
        ),
    ]
