# Generated by Django 5.0.6 on 2024-07-03 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_particpant_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interested', models.BooleanField(default=False)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressed_interests', to='user.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='user.participant')),
            ],
        ),
    ]
