# Generated by Django 5.0.6 on 2024-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_participant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='optimum_happiness',
            field=models.FloatField(default=0),
        ),
    ]
