# Generated by Django 5.0.6 on 2024-07-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_event_optimum_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='optimum_happiness',
            field=models.FloatField(default=0, null=True),
        ),
    ]
